### ISSUE TITLE
REPEATED functionality needed

### ISSUE THREAD

**Issue by pentium10** [kaizenplatform/fluent-plugin-bigquery#108]
We are actively using for event shipping the plugin, and now our `roles` field was changed recently in REPEATED mode. As far I know the plugin doesn't support yet repeated fields. Can this feature be added as high priority?

**Comment by pentium10** [comment]
@joker1007  what you say about this?

**Comment by joker1007** [comment]
This plugin has already supported to insert to REPEATED column.
I am using this with REPEATED column schema.

If schema description is written on fluent.conf by `field_string` or `field_float` etc,
this plugin does not have API for describing REPEATED column.
I think that fluent.conf is not suitable for it.
I recommend to use `schema_path` AND write schema desciption by JSON format.

ex.
https://github.com/kaizenplatform/fluent-plugin-bigquery/blob/master/test/plugin/testdata/apache.schema

**Comment by pentium10** [comment]
cool, indeed it does, but it worth mentioning on readme/documentation
