### ISSUE TITLE
Only Send Fields Matching the Schema

### ISSUE THREAD

**Issue by GLStephen** [kaizenplatform/fluent-plugin-bigquery#126]
Is it possible to add, or does the plugin already support, the ability to ignore fields that don't match the schema? We have some instances where inconsistent data flows into our fluentd. I would rather takes the fields that match, and drop just the fields, while taking all other fields that do match the schema. Is this possible? Basically, allow the schema to act like a sieve, instead of a block.

**Comment by yoheimuta** [comment]
Handling of fields not in the schema has changed around v0.3.0.

- https://github.com/kaizenplatform/fluent-plugin-bigquery/blob/v0.2.7/lib/fluent/plugin/out_bigquery.rb#L583
- https://github.com/kaizenplatform/fluent-plugin-bigquery/blob/v0.3.0/lib/fluent/plugin/bigquery/schema.rb#L204

In particular, if you are using the fetch_schema option, before v0.3.0, the procedure for adding columns did not result in an error regardless of the order in which the next operation was performed.

- sends data to td-agent
- update a bq table schema
- reload td-agent

There is a possibility that an error will occur unless the following order is followed now.

- update a bq table schema
- reload td-agent
- sends data to td-agent (especially when sending Map, Array to String field)

For example, if app sends data before bq table update, there is no column, so an error occurs (this can also be prevented by ignore_unknown_values). Also, if you send data(ex. Map to String field) before load, it will not be JSON encoded and will result in an error.

I do not want to depend on the order of releasing procedures when adding columns, so I want to ignore the fields that are not in the schema being loaded by the option.

How about that ?

### Error log excerpt

```
# JSON encoded error
2017-06-14 16:22:57 +0900 test.localhost: {"code":"1","is_bool":false,"params":"params","params_json":{"a":1,"b":2,"c":[1,2,3]}}

2017-06-14 16:22:59 +0900 [warn]: insert errors project_id="turnkey-conduit-708" dataset="test_mtburnlog" table="test_great_20170614" insert_errors="[#<Google::Apis::BigqueryV2::InsertAllTableDataResponse::InsertError:0x007fe387738cd8 @errors=[#<Google::Apis::BigqueryV2::ErrorProto:0x007fe387738288 @debug_info=\"generic::invalid_argument: This field is not a record.\", @location=\"params_json\", @message=\"This field is not a record.\", @reason=\"invalid\">], @index=0>]"
```

**Comment by GLStephen** [comment]
I don't need to update the schema at all. My goal would be to use the retrieved schema as a field filter and only send the fields that match, by name, the retrieved schema. That is the sort of functionality I need.

**Comment by GLStephen** [comment]
Nvm, ignore_unknown_vakues accomplishes what I need.
