### ISSUE TITLE
Warn with Buffer in Copy?

### ISSUE THREAD

**Issue by GLStephen** [kaizenplatform/fluent-plugin-bigquery#134]
I have config like this:

```
<match prod.project.push.myEvent>
  @type copy

  <store>
    @type bigquery
    @id mytable
    table mytable
    dataset mydataset

    auth_method compute_engine
    project myproject
    fetch_schema true
    <buffer>
      flush_interval 0.1  # flush as frequent as possible
      buffer_queue_limit 1024        # 1MB * 10240 -> 10GB!
      flush_thread_count 16
    </buffer>
  </store>
  <store>
    @type flowcounter
    tag prod.project.metric.myEvent
    unit minute
    aggregate all
  </store>
</match>
```

This config is emitting this sort of error in the logs:

2017-07-07 14:34:05 +0000 [warn]: parameter 'flush_interval' in <buffer>

Is this an issue with fluentd or with this plugin? Things seem to be working, but I'd like to resolve these warnings if possible.

**Comment by joker1007** [comment]
Please teach me fluentd version, plugins version, config about `flowcounter`, and more error logs

**Comment by GLStephen** [comment]
Fluentd 12
Plugin v0.4.4

These are the only relevant error logs. 

2017-07-11 22:03:44 +0000 [warn]: parameter 'flush_interval' in <buffer>
  flush_interval 0.1
  buffer_queue_limit 1024
  flush_thread_count 16
</buffer> is not used.

**Comment by joker1007** [comment]
Your configuration is invalid on fluentd-v0.12
`<buffer>` section is for fluentd-v0.14.x

**Comment by GLStephen** [comment]
You are entirely correct. I've updated the config and it is working as expected. Thanks!
