### ISSUE TITLE
Feature Request: Log Load Failures or Move Failed Logs

### ISSUE THREAD

**Issue by GLStephen** [kaizenplatform/fluent-plugin-bigquery#135]
We are moving many of our streaming jobs to load jobs because their volume of data has become very large. In streaming inserts a bad insert would fail and be put back into the retry queue. Load jobs are simply deleted. Is it possible to log these or move the buffer file somewhere on failure? Or is there some other way to handle this?

**Comment by joker1007** [comment]
I recommend to use file output as secondary output plugin.
http://docs.fluentd.org/v0.12/articles/output-plugin-overview#secondary-output

I use secondary output plugin, and re-load error files manually.

**Comment by Patrick-Shih** [comment]
hi @joker1007,

I have some "format" issue using secondary output plugin.  Sample config is as follow

```
<match ...>
  @type copy
  <store>
    @type bigquery
    method insert    # default
    ...
    <secondary>
      @type file
      path /var/log/td-agent/failed_event
      time_slice_format %Y%m%d
      time_slice_wait 10m
      time_format %Y%m%dT%H%M%S%z
      compress gzip
    </secondary>
  </store>
  <store>
    ...
  </store>
</match>
```

However, the input is json format but what logged in secondary file is something like a binary format

when I input
{"A":1, "B":2, "C":"test"}

I got following in the file 
��json��A�B�C�test�fluentTimestamp~�

With json format I can write script to resend it.  But I don't know how to resend it with this binary format manually?
