### ISSUE TITLE
support for multi worker like fluent-plugin-gcs

### ISSUE THREAD

**Issue by gyamxxx** [kaizenplatform/fluent-plugin-bigquery#136]
Fluentd v0.14.12 supports multi process workers.
https://www.fluentd.org/blog/fluentd-v0.14.12-has-been-released
but, this plugin was errored like this.
```
2017-07-26 16:49:31 +0900 [error]: config error file="/etc/td-agent/td-agent.conf" error_class=Fluent::ConfigError error="Plugin 'bigquery' does not support multi workers configurat
ion (Fluent::Plugin::BigQueryOutput)"
```
could you support multi process workers?

fluent-plugin-gcs may support multi process workers.
https://github.com/daichirata/fluent-plugin-gcs

**Comment by cosmo0920** [comment]
#137 is merged. This issue should be closed.

**Comment by joker1007** [comment]
Thanks.
