### ISSUE TITLE
Setup instructions

### ISSUE THREAD

**Issue by ashishtilara** [kaizenplatform/fluent-plugin-bigquery#147]
## Environments

- fluentd version: fluentd-0.12.35
- plugin version: N/A

I recently installed fluentd on ubuntu-trusty, and wondering how can I install this plugin. I am new to Fluentd setup.

Appreciate any help.

Thank you,
Ashish

**Comment by cosmo0920** [comment]
See Fluentd official document: https://docs.fluentd.org/v0.12/articles/plugin-management
