### ISSUE TITLE
Plugin Does not work Fully w/ > 0.9.x google-api-client

### ISSUE THREAD

**Issue by GLStephen** [kaizenplatform/fluent-plugin-bigquery#150]
This is in the gemspec 

spec.add_runtime_dependency "google-api-client", ">= 0.9.3", "< 0.14"

However timeout names and where they are set changed completely in 0.10

https://github.com/google/google-api-ruby-client/blob/8ef5c84c78f6eae4292be8c37ba901a847718dd7/MIGRATING.md

Running outside of 0.9.x causes load jobs to be unpredictable.

**Comment by joker1007** [comment]
@GLStephen Thanks!! I fixed it.
I will release new version soon.
