### ISSUE TITLE
Reload schema json on config reload (kill -HUP)

### ISSUE THREAD

**Issue by dobesv** [kaizenplatform/fluent-plugin-bigquery#158]
This doesn't seem to reload the bigquery schema json when I sent a HUP signal to fluentd.

**Comment by joker1007** [comment]
How do you write fluentd configuration?

When fluentd receive SIGHUP, supervisor process kills worker processes by sending SIGTERM.
After that, supervisor restart worker process automatically.
I think that configuration is reloaded regardless of plugin implementation.
