### ISSUE TITLE
Specify partition table

### ISSUE THREAD

**Issue by uudashr** [kaizenplatform/fluent-plugin-bigquery#161]
## Environments

- fluentd version: v.1.1.3-onbuild (docker)
- plugin version: 1.2.0

Thte extesion config for defining partition table on 1.2.0
```
<match dummy>
  @type bigquery_insert

  ...
  table   accesslog$%Y%m%d

  <buffer time>
    timekey 1d
  </buffer>
  ...
</match>
```

on the past version, it's capable of doing:
```
<match dummy>
  @type bigquery_insert

  ...
  table   accesslog$%Y%m%d@server_timestamp

  <buffer time>
    timekey 1d
  </buffer>
  ...
</match>
```

which the time key is taken from existing value. Is it possible to do this now?

**Comment by joker1007** [comment]
Sorry, This feature is removed from 1.0.0.
Because combination of filter plugin and buffer chunk key (by record property) realize same result.
I judged this feature is not main feature for fluent-plugin-bigquery.

I write an example.

```
<filter dummy>
  @type record_transformer
  enable_ruby
  <record>
    server_timestamp ${server_timestamp.strftime("%Y%m%d")}
  </record>
</filter>

<match dummy>
  @type bigquery_insert

  table accesslog$${server_timestamp}

  <buffer server_timestamp>
  <buffer>
</match>
```

Could you try this config style?

**Comment by uudashr** [comment]
The problem solved with official way using inject, but still curious.

Config:
```
<filter app.log>
  @type record_modifier
  
  <record>
    # Add server timestamp information
    server_timestamp  ${Time.now.to_i}
  </record>
</filter>

<match dummy>
  @type bigquery

  table accesslog$${Time.at(server_timestamp).strftime('%Y%m%d')}

  <buffer server_timestamp>
  <buffer>
</match>
```
The problem solved, but still curious. I try to apply then error:
```
accesslog$${Time.at(server_timestamp).strftime('%Y%m%d')}/fetch_schema_table=/template_suffix=' has timestamp placeholders, but chunk key 'time' is not configured
```

**Comment by joker1007** [comment]
The config example seems to be wrong
Built in placeholder only refer to value. It cannot evaluate ruby code.
If you want to use `strftime`, you must write it in record_modifier config.

**Comment by uudashr** [comment]
I see.. thanks
