### ISSUE TITLE
Column based partitioning cause BadRequest

### ISSUE THREAD

**Issue by katsew** [kaizenplatform/fluent-plugin-bigquery#175]
I specified the `time_partitioning_field` in my config and BigQuery returns BadRequest saying `Streaming to metadata partition of column based partitioning table...` .
I workaround by removing `$%Y%m%d` from `table` field.

## Environments

- fluentd version: v1.4.2
- plugin version: v2.1.0

## Configuration

```
<match **>
  @type bigquery_insert
  table   ${myTableName}$%Y%m%d
  schema [...]
  time_partitioning_type day
  time_partitioning_field loggedAt
  time_partitioning_require_partition_filter true
  <buffer myTableName,time>
    timekey 1d
  </buffer>
</match>
```

## Expected Behavior

Successfully inserted.

## Actual Behavior

BadRequest occurred.

## Log (if you have)

I had the same error as described in [here](https://stackoverflow.com/questions/49821226/streaming-into-column-based-partitioned-bigquery-table-disallowed)

## Additional

This behavior is different from what the document says, or misleading in my case.
I think it's good to have a note about this at [here](https://github.com/kaizenplatform/fluent-plugin-bigquery#date-partitioned-table-support).

**Comment by joker1007** [comment]
Thanks!
The document is wrong now. I will correct it.

**Comment by joker1007** [comment]
I have corrected. ecb10b0
