### ISSUE TITLE
Support for Record's timestamp key in formatting Table Id 

### ISSUE THREAD

**Issue by mohit-gupta** [kaizenplatform/fluent-plugin-bigquery#46]
Hi, 

We have a requirement where we want to be sure that records are going into the correct bigquery table based upon their timestamp. 
Currently, table ids are formatted based upon the local time of fluentd server.
"Note that the timestamp of logs and the date in the table id do not always match, because there is a time lag between collection and transmission of logs." I would like to know the reason behind this limitation. Also, I'm not familiar with Ruby, would it be possible to make some minor changes in the plugin and achieve the desired?

Thanks for your help.

**Comment by meotimdihia** [comment]
:+1: i am the same as you on this problem.

**Comment by FereshtehLL** [comment]
+1
We have the same requirement

**Comment by sakatam** [comment]
just took a glance.

timestamp for generating table id is fixed to local time here:
https://github.com/kaizenplatform/fluent-plugin-bigquery/blob/master/lib/fluent/plugin/out_bigquery.rb#L322

in order to improve this, need to take a config param to specify a timestamp filed for table id.
