### ISSUE TITLE
http proxy support

### ISSUE THREAD

**Issue by edwardchuang** [kaizenplatform/fluent-plugin-bigquery#48]
plugin is unable to use if there's http proxy required, please support http proxy

**Comment by bmcgavin** [comment]
Hi, I had this problem too - the google-api-ruby-client (v0.8.6) will respect the `http_proxy` environment variable (even though traffic is HTTPS), see https://github.com/google/google-api-ruby-client/blob/v0.8.6/lib/google/api_client.rb#L110

**Comment by joker1007** [comment]
Current google-api-client uses httpclient gem.
httpclient gem support `http_proxy` and `HTTP_PROXY` environment variable.
Please use this.
