### ISSUE TITLE
Support for json private key instead of p12

### ISSUE THREAD

**Issue by gvsrini** [kaizenplatform/fluent-plugin-bigquery#49]
Does this plugin support private key in json format? Google has deprecated p12 format now in favor of json. If the plugin already supports json, please mention the config in the README.

**Comment by tagomoris** [comment]
There're only `private_key` or `compute_engine`.
Pull requests are always welcome :D

**Comment by hakobera** [comment]
@gvsrini @tagomoris I think #50 satisfy your demands.
