### ISSUE TITLE
Could you bump up the gem version?

### ISSUE THREAD

**Issue by makimoto** [kaizenplatform/fluent-plugin-bigquery#90]
I'd like to use features added since v0.2.16 (especially my pull req, https://github.com/kaizenplatform/fluent-plugin-bigquery/pull/82).
So if there's any blocker, could you bump up the gem version and publish to rubygems.org?

**Comment by joker1007** [comment]
Thanks for this issue.
I have gotten release permission recently.
I am getting ready for relase next version. Please wait a bit.

**Comment by joker1007** [comment]
I have released new version v0.3.0.
